

CREATE TABLE IF NOT EXISTS "ver_admin"."profiles" ("id"  BIGSERIAL, "profileId" VARCHAR(64) NOT NULL, "configId" VARCHAR(64) DEFAULT NULL, "version" VARCHAR(16) DEFAULT NULL, "updatedBy" VARCHAR(64), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));